name: track_my_degree
description: "A Flutter app to help students track subjects, assignments, and study plans."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  sqflite: ^2.3.0
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  uuid: ^4.4.2
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  csv: ^6.0.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
